# Generated by Django 3.1 on 2020-08-27 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_m', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statistics',
            options={'verbose_name': 'Statistics', 'verbose_name_plural': 'Statistics'},
        ),
    ]
