# Generated by Django 3.1 on 2020-08-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_m', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistics',
            old_name='purchase',
            new_name='purchases',
        ),
    ]
