# Generated by Django 3.1 on 2020-10-21 15:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type of Purchase')),
                ('slug', models.SlugField(max_length=110, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cost $')),
                ('date', models.DateTimeField(default=datetime.datetime(2020, 10, 21, 15, 51, 57, 915500, tzinfo=utc), verbose_name='Created Date')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Type', to='main.type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
                'ordering': ['date'],
            },
        ),
    ]
