# Generated by Django 3.1 on 2020-08-22 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='Тип покупки')),
                ('cost', models.PositiveIntegerField(verbose_name='Стоимость')),
                ('slug', models.SlugField(max_length=110, unique=True, verbose_name='Url')),
                ('degree_of_importance', models.SmallIntegerField(default=0, verbose_name='Степень важности')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Когда была сделана покупка')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['date'],
            },
        ),
    ]
