# Generated by Django 3.1 on 2020-08-27 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200826_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='level',
        ),
        migrations.RemoveField(
            model_name='type',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='type',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='type',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='type',
            name='tree_id',
        ),
    ]
