# Generated by Django 3.1 on 2020-08-28 12:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200828_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 12, 8, 58, 254271, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
