# Generated by Django 3.1 on 2020-08-29 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20200829_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 29, 9, 33, 13, 959080, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
