# Generated by Django 3.1 on 2020-09-03 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200831_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 22, 9, 881748, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
