# Generated by Django 3.1 on 2020-09-03 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200903_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 3, 14, 43, 1, 17309, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
