# Generated by Django 3.1 on 2020-09-15 13:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200903_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 13, 53, 2, 579926, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
