# Generated by Django 3.1 on 2020-09-15 15:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200915_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 15, 15, 26, 55, 483109, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
