# Generated by Django 3.1 on 2020-09-17 11:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20200915_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 11, 20, 42, 946468, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
