# Generated by Django 3.1 on 2020-09-19 18:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200917_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 18, 13, 8, 97777, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
