# Generated by Django 3.1 on 2020-11-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='C:\\Users\\Alexey\\Documents\\Django projects\\PayTracker\\media/avatars/nophoto.jpg', upload_to='avatars', verbose_name='Avatar')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='Url')),
                ('bio', models.TextField(blank=True, max_length=200, verbose_name='Bio')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
